package devtaube.nanocad.editor.cmd;

import devtaube.nanocad.ObjectFileGenerator;
import rosequartz.RoseQuartz;
import rosequartz.files.FileManager;

public class SaveCommand extends Command {

    public static final String MATERIAL_FILE_PRESET = """
            # Generated by NanoCAD
            newmtl model_texture
            illum 1
            Ka 0.000 0.000 0.000
            Kd 1.000 1.000 1.000
            Ks 0.000 0.000 0.000
            map_Kd {}.png
            """;

    private final ObjectFileGenerator objGenerator = new ObjectFileGenerator();

    @Override
    public String[] getNames() { return new String[] { "save", "sv" }; }

    @Override
    public int[] getValidArgCounts() { return new int[] { 1 }; }

    @Override
    public String getArgUsage() { return "<model-name>"; }

    @Override
    public String getDescription() { return "Saves the model."; }

    @Override
    protected String run() {
        String modelName = getArgString(0);
        if(modelName.contains("/") || modelName.contains("\\"))
            throw new CommandException("Model name may not contain file system path separators.");
        try {
            String objText = objGenerator.generate(modelName);
            FileManager.get().writeFileString(modelName + ".obj", objText);
            FileManager.get().writeFileString(modelName + ".mtl", RoseQuartz.fmt(MATERIAL_FILE_PRESET, modelName));
            return "Saved model to \"/files/" + modelName + ".obj\".";
        } catch(Exception ignored) {
            throw new CommandException("Unable to save model file.");
        }
    }

}
